### ISSUE TITLE
Only display prefix "J." for numeric matchday on matches list

### ISSUE THREAD

**Issue by mbilbille** [oldergod/red#102]
Attribut `matchday` supports different data-type:
- Numerical ; basic case for league competition
- Textual ; for cup competition (`1e tour`, `1/2 finale`, etc.)

Therefore, on listing prefix `J.` is only pertinent on numerical matchday.

![screenshot_20170727-094431](https://user-images.githubusercontent.com/718938/28660055-d1f61592-72b1-11e7-9fea-cf39124a5f3f.png)

**Comment by oldergod** [comment]
Good to know, thank you!
