### ISSUE TITLE
Some team logos are not loaded

### ISSUE THREAD

**Issue by mbilbille** [oldergod/red#132]
Reproduced on Champions League fixtures

![screenshot_20171126-130309](https://user-images.githubusercontent.com/718938/33239827-d937fab0-d2aa-11e7-8b1b-27ee4317ea6d.png)

**Comment by oldergod** [comment]
Merci. Ca vient des accents dans le nom du pays qui n'est pas present dans l'url.
par exemple: j'essaye d'acceder `https://tvfoot.net/images/teams/gr%C3%A8ce/large/oly.png` tandis que c'est `https://tvfoot.net/images/teams/grece/large/oly.png`

**Comment by mbilbille** [comment]
Ah oui j'ai un bout de code pour échapper les noms des pays.

```js
/**
 * Normalizes the input url using the following rules:
 *  - lowercase
 *  - whitespace replace by -
 *  - accents are removed
 *
 * @param {String} url The URL to normalize
 */
angular.module('tvfoot').filter('normalizeURL', function() {
  return function(url) {
    var map = {
      'à':'a', 'á':'a', 'â':'a', 'ã':'a', 'ä':'a',
      'ç':'c',
      'è':'e', 'é':'e', 'ê':'e', 'ë':'e',
      'ì':'i', 'í':'i', 'î':'i', 'ï':'i',
      'ñ':'n',
      'ò':'o', 'ó':'o', 'ô':'o', 'õ':'o', 'ö':'o',
      'ù':'u', 'ú':'u', 'û':'u', 'ü':'u',
      'ý':'y', 'ÿ':'y',
      '&': 'and' // Hack to fix #44
    };
    return url.toLowerCase().replace(/\s+/g, '-').replace(/\W/g, function(c) {return map[c] || c;}).replace(/\/-|-\//g, '/');
  };
});
`

**Comment by oldergod** [comment]
J'ai laisse Java s'en occuper moi. On verra si ca regle tout les problemes.
