### ISSUE TITLE
MVI implementation in this project vs your "clean-architecture" project.

### ISSUE THREAD

**Issue by VasileUngureanu** [oldergod/red#138]
Hi,
Interesting to know in witch project you think that MVI pattern is implemented better?
I mean in witch project you analyzed more on how to apply MVI.

I'm asking this to choose one of them to be as the source of inspiration for me ))

Thanks!

**Comment by oldergod** [comment]
Hey Vasile, I don't have any clean-architecture project, I guess you're talking about the "android-architecture". Except the fact that `red` is written fully in Kotlin there isn't really much difference between the two; I usually update both when I found a better way to implement something.
The kotlin code is of course easier to read :)

**Comment by VasileUngureanu** [comment]
Yes! "android-architecture" ))

This is great if you apply fresh ideas on both.
In this case we have great source of inspiration for both languages (Java, Kotlin).

Thanks!
