### ISSUE TITLE
Filter by team

### ISSUE THREAD

**Issue by oldergod** [oldergod/red#140]
started with #137 

- [x] empty view
- [x] clear search and search result when team is selected
- [x] do not display search result after field has been deleted
- [x] ok button to close drawer
- [x] search icon for input
- [x] header to better identify filters
- [x] logo des equipes filtrees

**Comment by mbilbille** [comment]
J'aime bien la recherche, la présentation des résultats par contre j'aurai plus vu ça dans un autre panel que celui des filtres.

Autre question? Suite à la recherche quand tu as sélectionné une team il faudrait pas cleaner:
1/ le champ de recherche
2/ le résultat de recherche

**Comment by mbilbille** [comment]
Un bug cette fois (si tu décides d'intégrer ça au panel de filtres) ; il manque le bouton avec la croix quand tu sélectionnes une équipe. Le bouton apparaît uniquement si tu sélectionnes un compétition.
Et le bouton ne cleane que les filtres de compétitions également.

PS: Je déteste ce bouton j'ai toujours l'impression que c'est pour fermer le panel de filtre, je me trompe une fois sur 2

**Comment by oldergod** [comment]
done with #142
