### ISSUE TITLE
Track usage

### ISSUE THREAD

**Issue by mbilbille** [oldergod/red#67]
Support Google Analytics to track app vs. web usage

**Comment by oldergod** [comment]
@mbilbille tu voudrais quoi idealement ?

**Comment by mbilbille** [comment]
A minima, consolider l'ensemble des visites web et mobile sur le même tracker, et de pouvoir ensuite filtrer sur le type de visites, desktop, mobile, app. Je ne sais pas si Google propose ce genre de chose out of the box?

**Comment by oldergod** [comment]
sur Android, sur de-facto c'est Firebase. Google Analytics a pas ete integre d'ailleurs dessus ?
https://firebase.google.com/docs/analytics/

On dirait que non mais Google a rachete Firebase il y a deja quelques mois.

**Comment by mbilbille** [comment]
J'ai pas l'impression que tu puisses consolider les 2 sources d'informations... c'est bien dommage
https://support.google.com/analytics/answer/6392697

Par contre on dirait que tu peux brancher Google Analytics sur ton app: https://developers.google.com/analytics/solutions/mobile

**Comment by oldergod** [comment]
Si ca te fait plaisir, je mets GA alors

**Comment by mbilbille** [comment]
C'est pas juste pour me faire plaisir :) Juste indispensable de suivre l'usage du site.

**Comment by oldergod** [comment]
Je veux dire que je comptais mettre Firebase. Je te dis quand je le fais car j'aurais surement besoin que tu me fournisses les credentials de ton tracker a un moment ou un autre.

**Comment by mbilbille** [comment]
Tu peux peut être les deux? 
J'ai rapidement survoler Firebase Analytics il a l'air plus poussé pour le tracking mobile.

Google Analytics c'est surtout pour avoir une vue globale du traffic

**Comment by oldergod** [comment]
C'est pas cool pour le user donc je vais trancher.

2017-04-30 21:42 GMT+09:00 Matthieu Bilbille <notifications@github.com>:

**Comment by mbilbille** [comment]
Pourquoi c'est pas cool?
Ca rajoute des permissions à accepter?

**Comment by oldergod** [comment]
Je veux pas utiliser le network si j'en ai pas besoin par exemple. Ensuite
rajouter une lib en plus augmente la taille de l'APK, ce genre de chose.

2017-04-30 22:08 GMT+09:00 Matthieu Bilbille <notifications@github.com>:

**Comment by mbilbille** [comment]
Tu as intégré Firebase Analytics alors ?
