### ISSUE TITLE
Texte tronqué dans le listing des matchs

### ISSUE THREAD

**Issue by mbilbille** [oldergod/red#84]
Il y a certains textes tronqués dans la description sous les deux noms d'équipes.
![screenshot_20170606-003933](https://cloud.githubusercontent.com/assets/718938/26806759/dd2b40fe-4a52-11e7-8a29-606d1892c2c2.png)

**Comment by mbilbille** [comment]
On voit même un "Tou" à la suite de 2018 je ne sais pas d'où cela provient

**Comment by oldergod** [comment]
C'est "Tour 1". Je vais faire un retour a la ligne dans ce cas la. Merci.

**Comment by oldergod** [comment]
Tu peux voir ce que c'est en mettant ton telephone en mode landscape :p

**Comment by mbilbille** [comment]
Oui c'est vrai.
Y a d'autres descriptions où c'est coupé genre "demi-finale"

**Comment by oldergod** [comment]
fixed by #90
