### ISSUE TITLE
Format des dates

### ISSUE THREAD

**Issue by mbilbille** [oldergod/red#85]
Les dates dans le listing des matchs pourraient être dans un format un peu plus sexy :)
 
Par exemple `2017-06-07` remplacé par `MERCREDI, 07 JUIN 2017`

**Comment by oldergod** [comment]
Yep, meme enlever l'annee ou le mois, si ce n'est pas pertinent

**Comment by mbilbille** [comment]
Oui on peut se passer de l'année, mais c'est pour être consistant avec le site 😁.
Par contre le jour de la semaine c'est une information importante
